---
- name: XR Router Troubleshooting
  hosts: XR
  gather_facts: false
  connection: network_cli

  vars:
    ###name: ansible_IOSXR
      ansible_network_os: iosxr
      ansible_user: cisco123
      ansible_ssh_pass: cisco123


  tasks:
    - name: Core Troubleshooting Commands
      iosxr_command:
        commands:
          - "{{item}}"

      with_items:
          - show clock
          - show platform
          - show redundancy
          - show proc cpu | ex "0%      0%       0%"
          - show memory sum location all | in "node|Pyhsical|available"
          - show int description | i down
          - show log | i, ch

      register: iosxr_mon

    - name: Clock Check
      debug:
         msg:
           - "{{ inventory_hostname }} Clock "
           - "{{ iosxr_mon.results[0].stdout_lines }}"

    - name: Platform Hardware Check
      debug:
        msg:
          - "{{ inventory_hostname }} show_platform indicates card is down: "
      when: '"Down" in iosxr_mon.results[1].stdout[0]'

    - name: Redundancy Check
      debug:
        msg: "{{ inventory_hostname }} show_redundancy indicates card is not present: "
      when: '"NSR not ready since Standby is not Present" and "has no valid partner" in iosxr_mon.results[2].stdout[0]'

    - name: CPU Utilization Check
      debug:
         msg:
           - "{{ inventory_hostname }} CPU Utilization "
           - "{{ iosxr_mon.results[3].stdout_lines }}"

    - name: Memory Utilization Check
      debug:
        msg:
          - "{{ inventory_hostname }} Memory Utilization: "
          - "{{ iosxr_mon.results[4].stdout_lines }}"

    - name: Down Interface Checks
      debug:
        msg: "{{ inventory_hostname }} Interface is Down: "
      when: '"down" in iosxr_mon.results[5].stdout[0]'

    - name: check if any link flapped or down
      debug:
        msg:
          - "{{ inventory_hostname }} logs "
          - "{{ iosxr_mon.results[6].stdout_lines }}"

    - name: Save output to a file
      copy:
        content="\n\n ===show clock=== \n\n{{ iosxr_mon.results[0].stdout_lines }}\n\n ===show platform=== \n\n{{ iosxr_mon.results[1].stdout_lines }}\n\n ===sh int description=== \n\n{{ iosxr_mon.results[5].stdout }}\n\n ===show redundancy===\n\n{{ iosxr_mon.results[2].stdout }}\n\n ===show proc cpu===\n\n{{ iosxr_mon.results[3].stdout }}\n\n ===show memory sum location all=== \n\n{{ iosxr_mon.results[4].stdout }}\n\n ===sh log=== \n\n{{ iosxr_mon.results[6].stdout }}"
        dest="./{{ inventory_hostname }}_health_check.csv"
...
